vidyomonit/app/connections_manager/views.py
"""
This file is part of the CERN Dashboards for Vidyo
Copyright (C) 2014 European Organization for Nuclear Research (CERN)

CERN Dashboards for Vidyo is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

CERN Dashboards for Vidyo is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with the CERN Dashboards for Vidyo software.  If not, see <http://www.gnu.org/licenses/>.
"""

from flask import Blueprint, g, render_template, abort, redirect, url_for, request, jsonify, flash

from vidyomonit.app.connections_manager.forms import process_device_family_add_form, process_device_family_delete_form, \
    process_device_family_edit, process_device_add, process_device_edit, process_device_delete
from vidyomonit.app.connections_manager.gateways.forms import process_gateway_add, process_gateway_delete, \
    process_gateway_edit
import rethinkdb as r

module = Blueprint('connections_manager', __name__)


@module.route('/operating-systems', methods=['GET', 'POST'])
def operating_systems():
    device_type = 'app_os'
    device_print_name = 'Operating System'

    device_families_forms = get_device_families_forms(device_type, device_print_name)
    device_forms = get_device_forms(device_type, device_print_name)

    if request.method == 'POST':
        redirect(url_for('connections_manager.operating_systems'))

    device_families = list(r.table('connections_groups').filter({'type': device_type}).order_by('name').run(g.rdb_conn))
    device_families_keys = [os_f['id'] for os_f in device_families]
    devices = list(r.table('connections_groups_devices').filter(
        lambda device:
        device['connections_group'] in device_families_keys and device['type'] == device_type
    ).order_by('name').merge(lambda device: {
        'device_family': r.table('connections_groups').get(device['connections_group'])
    }).run(g.rdb_conn))

    grouped_devices_names = get_grouped_devices_names_from_devices_list(devices)
    ungrouped_devices = get_ungrouped_devices(device_type, grouped_devices_names)

    return render_template('connections_manager/operating_systems.html', device_families_forms=device_families_forms,
                           device_forms=device_forms, devices=devices, device_families=device_families,
                           device_print_name=device_print_name, ungrouped_devices=ungrouped_devices)


@module.route('/application-versions', methods=['GET', 'POST'])
def application_versions():
    device_type = 'app_version'
    device_print_name = 'Application Version'

    device_families_forms = get_device_families_forms(device_type, device_print_name)
    device_forms = get_device_forms(device_type, device_print_name)

    if request.method == 'POST':
        redirect(url_for('.application_versions'))

    device_families = list(r.table('connections_groups').filter({'type': device_type}).order_by('name').run(g.rdb_conn))
    device_families_keys = [os_f['id'] for os_f in device_families]
    devices = list(r.table('connections_groups_devices').filter(
        lambda device:
        device['connections_group'] in device_families_keys and device['type'] == device_type
    ).order_by('name').merge(lambda device: {
        'device_family': r.table('connections_groups').get(device['connections_group'])
    }).run(g.rdb_conn))

    grouped_devices_names = get_grouped_devices_names_from_devices_list(devices)
    ungrouped_devices = get_ungrouped_devices(device_type, grouped_devices_names)

    return render_template('connections_manager/application_versions.html', device_families_forms=device_families_forms,
                           device_forms=device_forms, devices=devices, device_families=device_families,
                           device_print_name=device_print_name, ungrouped_devices=ungrouped_devices)


@module.route('/endpoint-types', methods=['GET', 'POST'])
def endpoint_types():
    device_type = 'endpoint_type'
    device_print_name = 'Endpoint Type'

    device_families_forms = get_device_families_forms(device_type, device_print_name)
    device_forms = get_device_forms(device_type, device_print_name)

    if request.method == 'POST':
        redirect(url_for('.endpoint_types'))

    device_families = list(r.table('connections_groups').filter({'type': device_type}).order_by('name').run(g.rdb_conn))
    device_families_keys = [os_f['id'] for os_f in device_families]
    devices = list(r.table('connections_groups_devices').filter(
        lambda device:
        device['connections_group'] in device_families_keys and device['type'] == device_type
    ).order_by('name').merge(lambda device: {
        'device_family': r.table('connections_groups').get(device['connections_group'])
    }).run(g.rdb_conn))

    grouped_devices_names = get_grouped_devices_names_from_devices_list(devices)
    ungrouped_devices = get_ungrouped_devices(device_type, grouped_devices_names)

    return render_template('connections_manager/endpoint_types.html', device_families_forms=device_families_forms,
                           device_forms=device_forms, devices=devices, device_families=device_families,
                           device_print_name=device_print_name, ungrouped_devices=ungrouped_devices)


@module.route('/gateway-names', methods=['GET', 'POST'])
def gateway_names():
    gateway_print_name = 'Gateway'
    gateway_forms = get_gateway_forms(gateway_print_name)

    if request.method == 'POST':
        redirect(url_for('.gateway_names'))

    gateways = list(r.table('gateways').order_by('name').run(g.rdb_conn))

    return render_template('connections_manager/gateways.html',
                           gateway_forms=gateway_forms,
                           gateways=gateways,
                           gateway_print_name=gateway_print_name
                           )


def get_device_families_forms(device_type='', device_print_name=''):
    return {
        'add': process_device_family_add_form(device_type=device_type,
                                              device_print_name=device_print_name),
        'delete': process_device_family_delete_form(device_print_name=device_print_name),
        'edit': process_device_family_edit(device_print_name=device_print_name)
    }


def get_device_forms(device_type='', device_print_name=''):
    return {
        'add': process_device_add(device_type=device_type, device_print_name=device_print_name),
        'edit': process_device_edit(device_print_name=device_print_name),
        'delete': process_device_delete(device_print_name=device_print_name)
    }


def get_gateway_forms(gateway_print_name=''):
    return {
        'add': process_gateway_add(gateway_print_name=gateway_print_name),
        'edit': process_gateway_edit(gateway_print_name=gateway_print_name),
        'delete': process_gateway_delete(gateway_print_name=gateway_print_name)
    }


def get_ungrouped_devices(device_type='', grouped_devices=[]):
    selection = r.table('connections_per_day').order_by('id').run(g.rdb_conn)
    devices = []
    for s in selection:
        for t in s['tenants']:
            connections = s['tenants'][t]['connections']
            devices_in_type = connections[device_type]
            if devices_in_type:
                for device_name in connections[device_type].keys():
                    if device_name not in devices:
                        devices.append(device_name)

    unique_devices_names_hashlist = sorted(set(devices) - set(grouped_devices))
    return unique_devices_names_hashlist


def get_grouped_devices_names_from_devices_list(devices_list):
    grouped_devices_names = []
    for device in devices_list:
        grouped_devices_names.append(device['name'])
    return grouped_devices_names

vidyomonit/app/views/admin_panel_old.py
"""
This file is part of the CERN Dashboards for Vidyo
Copyright (C) 2014 European Organization for Nuclear Research (CERN)

CERN Dashboards for Vidyo is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

CERN Dashboards for Vidyo is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with the CERN Dashboards for Vidyo software.  If not, see <http://www.gnu.org/licenses/>.
"""

from flask import Blueprint, render_template

module = Blueprint('module_view_devices', __name__)

@module.route('/', methods=['GET'])
def admin_panel():
    return render_template('admin_panel.html')

vidyomonit/app/views/manager.py
"""
This file is part of the CERN Dashboards for Vidyo
Copyright (C) 2014 European Organization for Nuclear Research (CERN)

CERN Dashboards for Vidyo is free software: you can redistribute it and/or
modify it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

CERN Dashboards for Vidyo is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with the CERN Dashboards for Vidyo software.  If not, see <http://www.gnu.org/licenses/>.
"""

from flask import Blueprint, render_template, url_for, redirect, abort
from jinja2 import TemplateNotFound

module = Blueprint('manager', __name__)

@module.route('/', methods=['GET'])
def index():
    return redirect(url_for('manager.home'))


@module.route('/home')
def home():
    try:
        # if "user" in session:
        #     pass
        #     #current_app.logger.debug("Welcome {name}".format(name=session["user"]["nickname"]))
        return render_template('home.html')
    except TemplateNotFound:
        abort(404)

@module.route('/network-devices')
def network_devices():
    return render_template('network_devices.html')

vidyomonit/app/templates/admin_panel_old.html
<!--
    This file is part of the CERN Dashboards for Vidyo
    Copyright (C) 2014 European Organization for Nuclear Research (CERN)

    CERN Dashboards for Vidyo is free software: you can redistribute it and/or
    modify it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    CERN Dashboards for Vidyo is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with the CERN Dashboards for Vidyo software.  If not, see <http://www.gnu.org/licenses/>.
-->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidyo monit admin frontend</title>

    <link rel="stylesheet" href="static/css/vidyo-dashboard-style.css">

    <script src="static/js/jquery.min.js"></script>
    <script src="static/js/typeahead.jquery.min.js"></script>
    <script src="static/js/typeahead.bundle.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/vidyo-admin-dashboard-bundle.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div style="width: 80%; margin: auto;">
      <div style="border-radius: 10px; border: 1px solid #B6B6B6; padding: .2em;">
        <div id="vidyo-admin-dashboard"></div>
      </div>
    </div>

    <script>
    'use strict';
    /* global google, VidyoDashboard */
    var vidyoAdminDashboard;


    // Config options are explained in src/js/vidyo-admin-dashboard/vidyo-admin-dashboard.js
    var config = {
        targetId: 'vidyo-admin-dashboard',
        url: 'api/admin/'
    };

    vidyoAdminDashboard = new VidyoAdminDashboard(config);

    // vidyoAdminDashboard.unmount(); <-- can be used to delete dashboard from DOM
    </script>
  </body>
</html>

vidyomonit/app/templates/base.html
{#
    This file is part of the CERN Dashboards for Vidyo
    Copyright (C) 2014 European Organization for Nuclear Research (CERN)

    CERN Dashboards for Vidyo is free software: you can redistribute it and/or
    modify it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    CERN Dashboards for Vidyo is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with the CERN Dashboards for Vidyo software.  If not, see <http://www.gnu.org/licenses/>.
#}

<html>
<head>
    <title>{% block title %}Vidyo Dashboards manager{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/main.css"/>
    <link rel="stylesheet" href="/static/css/toolbar.css"/>
    <link rel="stylesheet" href="/static/bower_components/Materialize/dist/css/materialize.min.css"
          media="screen,projection"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block css %}{% endblock %}

    <!--<script src="/static/bower_components/jquery/dist/jquery.min.js" type="text/javascript"></script>-->
    <!--<script src="/static/bower_components/Materialize/dist/js/materialize.min.js" type="text/javascript"></script>-->

	  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
    {% block script %}{% endblock %}

</head>
<body>
{% set navigation_bar = [
    (url_for('manager.home'), 'home', 'home'),
    (url_for('static', filename="docs/html/index.html"), 'help', 'help')
] -%}
{% set active_page = active_page|default('home') -%}

{% from "cern_toolbar/macros.html" import render_cern_toolbar %}
{{ render_cern_toolbar() }}
<header>
    <nav class="blue">
        <div class="container">
            <div class="nav-wrapper">
                <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
                <a href="#" class="brand-logo">Vidyo Dashboards manager</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    {% for href, id, caption in navigation_bar %}
                        <li {% if id == main_page %} class="active"{% endif %}><a href="{{ href|e }}"><i
                                class="material-icons">{{ caption|e }}</i></a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<main>
    <div class="{% if active_page != 'network_devices' %}container{% endif %}">
        <div id="header">{% block header %}{% endblock %}</div>
        <div id="messages-wrap">
            <div id="messages">
                {% for category, msg in get_flashed_messages(with_categories=true) %}
                    <div class="chip light-green lighten-1">
                        <span class="message flash-{{ category }}">{{ msg }}</span>
                        <i class="material-icons">close</i>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div id="content">{% block content %}{% endblock %}</div>
        <div id="footer">{% block footer %}{% endblock %}</div>
    </div>
</main>

<ul id="slide-out" class="side-nav fixed" style="left: 0px;">
    <li class="bold {% if 'home' == active_page %}active{% endif %} side-nav-header"><a
            href="{{ url_for('manager.home') }}"
            class="waves-effect waves-light"><i
            class="material-icons">home</i> Home</a>
    </li>
    <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            <li class="bold">
                <a href="{{ url_for('manager.network_devices') }}"
                    class="collapsible-header  waves-effect waves-light
                    {% if 'network_devices' == active_page %}active{% endif %}">
                    <i class="material-icons">router</i>
                    Network Devices
                </a>
            </li>
        </ul>
    </li>
    <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            <li class="bold"><a
                    class="collapsible-header  waves-effect waves-light
                    {% if 'connections_os' == active_page %}active{% endif %}
                    {% if 'connections_app_versions' == active_page %}active{% endif %}
                    {% if 'connections_endpoint_types' == active_page %}active{% endif %}
                    {% if 'connections_gateway_names' == active_page %}active{% endif %}
                    ">
                <i class="material-icons">device_hub</i>
                Connections
            </a>
                <div class="collapsible-body" style="">
                    <ul>
                        <li class="{% if 'connections_app_versions' == active_page %}active{% endif %}"><a
                                href="{{ url_for('connections_manager.application_versions') }}">Application Version</a></li>
                    </ul>
                    <ul>
                        <li class="{% if 'connections_os' == active_page %}active{% endif %}">
                            <a href="{{ url_for('connections_manager.operating_systems') }}">Operating System</a>
                        </li>
                    </ul>
                    <ul>
                        <li class="{% if 'connections_endpoint_types' == active_page %}active{% endif %}"><a
                                href="{{ url_for('connections_manager.endpoint_types') }}">Endpoint Type</a></li>
                    </ul>
                    <ul>
                        <li class="{% if 'connections_gateway_names' == active_page %}active{% endif %}"><a
                                href="{{ url_for('connections_manager.gateway_names') }}">Gateways</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </li>
</ul>

</body>
<script type="text/javascript">
    $(".button-collapse").sideNav();
</script>
{% block extra_javascripts %}{% endblock %}
</html>

vidyomonit/app/templates/home.html
{#
    This file is part of the CERN Dashboards for Vidyo
    Copyright (C) 2014 European Organization for Nuclear Research (CERN)

    CERN Dashboards for Vidyo is free software: you can redistribute it and/or
    modify it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    CERN Dashboards for Vidyo is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with the CERN Dashboards for Vidyo software.  If not, see <http://www.gnu.org/licenses/>.
#}

{% extends "base.html" %}
{% set active_page = "about" %}
{% set main_page = "main" %}
{% block content %}
    <h1>About</h1>
    <p>From this site you can manage Vidyo Dashboards.</p>

    </table>
{% endblock %}

vidyomonit/app/templates/network_devices.html
{#
    This file is part of the CERN Dashboards for Vidyo
    Copyright (C) 2014 European Organization for Nuclear Research (CERN)

    CERN Dashboards for Vidyo is free software: you can redistribute it and/or
    modify it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    CERN Dashboards for Vidyo is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with the CERN Dashboards for Vidyo software.  If not, see <http://www.gnu.org/licenses/>.
#}

{% extends "base.html" %}
{% set active_page = "network_devices" %}
{% set main_page = "main" %}

{% block css %}
    <link rel="stylesheet" href="static/css/vidyo-dashboard-style.css">
{% endblock %}

{% block script%}
    <script src="static/js/typeahead.jquery.min.js"></script>
    <script src="static/js/typeahead.bundle.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/vidyo-admin-dashboard-bundle.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
{% endblock %}
{% block content %}
    <div id="vidyo-admin-dashboard"></div>

    <script>
    'use strict';
    /* global google, VidyoDashboard */
    var vidyoAdminDashboard;


    // Config options are explained in src/js/vidyo-admin-dashboard/vidyo-admin-dashboard.js
    var config = {
        targetId: 'vidyo-admin-dashboard',
        url: 'api/admin/'
    };

    vidyoAdminDashboard = new VidyoAdminDashboard(config);

    // vidyoAdminDashboard.unmount(); <-- can be used to delete dashboard from DOM
    </script>
{% endblock %}